<?php

namespace Database\Seeders;

use App\Models\Task;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "task"     => "Look at your finances and find one way to save money",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go for a walk",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Organize a cluttered drawer",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go to an escape room",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Write a list of things you are grateful for",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Study a foreign language",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Pick up litter around your favorite park",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make homemade ice cream",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Watch a movie you'd never usually watch",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Prepare a dish from a foreign culture",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Cook something together with someone",
                "category" => "cook",
                "person"    => 2,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Mow your neighbor's lawn",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go on a fishing trip with some friends",
                "category" => "social",
                "person"    => 3,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Repaint a room in your house",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Go swimming with a friend",
                "category" => "social",
                "person"    => 2,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Have a paper airplane contest with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Volunteer and help out at a senior center",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Host a movie marathon with some friends",
                "category" => "social",
                "person"    => 3,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Plant a tree",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Start a daily journal",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Take a class at your local community center that interests you",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Solve a Rubik's cube",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make your own LEGO creation",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to french braid hair",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go for a run",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Mow your lawn",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Hold a yard sale",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Have a jam session with your friends",
                "category" => "music",
                "person"    => 5,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn the NATO phonetic alphabet",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/NATO_phonetic_alphabet",
            ],
            [
                "task"     => "Start a garden",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Organize your pantry",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to use a french press",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://en.wikipedia.org/wiki/French_press",
            ],
            [
                "task"     => "Invite some friends over for a game night",
                "category" => "social",
                "person"    => 4,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go to a concert with local artists with some friends",
                "category" => "social",
                "person"    => 3,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Prepare a 72-hour kit",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "https://www.ready.gov/kit",
            ],
            [
                "task"     => "Do a jigsaw puzzle",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://en.wikipedia.org/wiki/Jigsaw_puzzle",
            ],
            [
                "task"     => "Learn origami",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Volunteer at your local food bank",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Volunteer at your local food pantry",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn to play a new instrument",
                "category" => "music",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Text a friend you haven't talked to in a long time",
                "category" => "social",
                "person"    => 2,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn woodworking",
                "category" => "DIY",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Write a note of appreciation to someone",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Take a spontaneous road trip with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn Express.js",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://expressjs.com/",
            ],
            [
                "task"     => "Play basketball with a group of friends",
                "category" => "social",
                "person"    => 5,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Listen to your favorite album",
                "category" => "music",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Play a volleyball match with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Fill out a basketball bracket",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make bread from scratch",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Clean out your garage",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go see a Broadway production",
                "category" => "fun",
                "person"    => 4,
                "cost"     => "$$$",
                "link"     => "",
            ],
            [
                "task"     => "Go to a local thrift shop",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Write a handwritten letter to somebody",
                "category" => "social",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Clean out your refrigerator",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make a scrapbook with pictures of your favorite memories",
                "category" => "DIY",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Shred old documents you don't need anymore",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Surprise your significant other with something considerate",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make a simple musical instrument",
                "category" => "music",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Listen to a new music genre",
                "category" => "music",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn Javascript",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Color",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Play a game of Monopoly",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to write in shorthand",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Take a hike at a local park",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Start a blog for something you're passionate about",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn Kotlin",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://kotlinlang.org/",
            ],
            [
                "task"     => "Go stargazing",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to play a new sport",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Create a compost pile",
                "category" => "DIY",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Do yoga",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Donate blood at a local blood center",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://www.redcross.org/give-blood",
            ],
            [
                "task"     => "Go see a movie in theaters with a few friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Watch the sunset or the sunrise",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Plan a trip to another country",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make a new friend",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Start a book you've never gotten around to reading",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Go to the library and find an interesting book",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn how the internet works",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Have a photo session with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Organize your basement",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to use an Arduino",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://en.wikipedia.org/wiki/Arduino",
            ],
            [
                "task"     => "Learn GraphQL",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://graphql.org/",
            ],
            [
                "task"     => "Learn how to fold a paper crane",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn a new recipe",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn to write with your nondominant hand",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn the Chinese erhu",
                "category" => "music",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Find a DIY to do",
                "category" => "DIY",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Take your dog on a walk",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Visit a nearby museum",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Back up important computer files",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Take a bubble bath",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Organize your music collection",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Give your pet ten minutes of focused attention",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go to a music festival with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Memorize the fifty states and their capitals",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go to a karaoke bar with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Uninstall unused apps from your devices",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make a to-do list for your week",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Read a formal research paper on an interesting subject",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Have a picnic with some friends",
                "category" => "social",
                "person"    => 3,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Have a bonfire with your close friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Hold a video game tournament with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Listen to a new podcast",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Explore a park you have never been to before",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Have a football scrimmage with some friends",
                "category" => "social",
                "person"    => 8,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Organize your dresser",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Pot some plants and put them around your house",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Bake something you've never tried before",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Learn about the Golden Ratio",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://en.wikipedia.org/wiki/Golden_ratio",
            ],
            [
                "task"     => "Draft your living will",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://www.investopedia.com/terms/l/livingwill.asp",
            ],
            [
                "task"     => "Create and follow a savings plan",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Plan a vacation you've always wanted to take",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to make an Alexa skill",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://developer.amazon.com/en-US/docs/alexa/custom-skills/steps-to-build-a-custom-skill.html",
            ],
            [
                "task"     => "Rearrange and organize your room",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Do something you used to do as a kid",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Start a band",
                "category" => "music",
                "person"    => 4,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Sit in the dark and listen to your favorite music with no distractions",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make a couch fort",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Compliment someone",
                "category" => "social",
                "person"    => 2,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Conquer one of your fears",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn a new programming language",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Catch up with a friend over a lunch date",
                "category" => "social",
                "person"    => 2,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Organize a bookshelf",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Find a charity and donate to it",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Do something nice for someone you care about",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Bake pastries for you and your neighbor",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Match your storage containers with their lids",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Create or update your resume",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Donate to your local food bank",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Learn the periodic table",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Periodic_table",
            ],
            [
                "task"     => "Play a video game",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn and play a new card game",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://www.pagat.com",
            ],
            [
                "task"     => "Visit your past teachers",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Watch a Khan Academy lecture on a subject of your choosing",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://www.khanacademy.org/",
            ],
            [
                "task"     => "Create a meal plan for the coming week",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Memorize a favorite quote or poem",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Pull a harmless prank on one of your friends",
                "category" => "social",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Volunteer at a local animal shelter",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn to sew on a button",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Start a collection",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Write a poem",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Write a short story",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Wash your car",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Configure two-factor authentication on your accounts",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Multi-factor_authentication",
            ],
            [
                "task"     => "Shop at support your local farmers market",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn to greet someone in a new language",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Write a song",
                "category" => "music",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Fix something that's broken in your house",
                "category" => "DIY",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Go to a concert with some friends",
                "category" => "social",
                "person"    => 4,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Meditate for five minutes",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make tie dye shirts",
                "category" => "DIY",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Go to the gym",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Patronize a local independent restaurant",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Draw and color a Mandala",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://en.wikipedia.org/wiki/Mandala",
            ],
            [
                "task"     => "Go on a long drive with no music",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Create a cookbook with your favorite recipes",
                "category" => "cook",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to whistle with your fingers",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Practice coding in your favorite lanaguage",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Start a webinar on a topic of your choice",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Take your cat on a walk",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to make a website",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Bake a pie with some friends",
                "category" => "cook",
                "person"    => 3,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Draw something interesting",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Think of a new business idea",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Make a bucket list",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Go to a nail salon",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Catch up on world news",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Look at pictures and videos of cute animals",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Buy a new house decoration",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$$",
                "link"     => "",
            ],
            [
                "task"     => "Take a caffeine nap",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn about a distributed version control system such as Git",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Distributed_version_control",
            ],
            [
                "task"     => "Take a nap",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Improve your touch typing",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Touch_typing",
            ],
            [
                "task"     => "Listen to music you haven't heard in a while",
                "category" => "music",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Start a family tree",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Family_tree",
            ],
            [
                "task"     => "Learn Morse code",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Morse_code",
            ],
            [
                "task"     => "Organize your movie collection",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to beatbox",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "https://en.wikipedia.org/wiki/Beatboxing",
            ],
            [
                "task"     => "Paint the first thing you see",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Try a food you don't like",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Learn how to iceskate or rollerskate",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Play a game of tennis with a friend",
                "category" => "social",
                "person"    => 2,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Make a budget",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Watch a classic movie",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Write a thank you letter to an influential person in your life",
                "category" => "social",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Research a topic you're interested in",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Create a personal website",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Contribute code or a monetary donation to an open-source software project",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "https://github.com/explore",
            ],
            [
                "task"     => "Learn calligraphy",
                "category" => "learn",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Binge watch a trending series",
                "category" => "fun",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Teach your dog a new trick",
                "category" => "resting",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Resolve a problem you've been putting off",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Clean out your closet and donate the clothes you've outgrown",
                "category" => "charity",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
            [
                "task"     => "Explore the nightlife of your city",
                "category" => "social",
                "person"    => 1,
                "cost"     => "$",
                "link"     => "",
            ],
            [
                "task"     => "Clean out your car",
                "category" => "staying busy",
                "person"    => 1,
                "cost"     => "free",
                "link"     => "",
            ],
        ];

        foreach ($data as $task){
            Task::create($task);
        }

    }
}
