<?php

namespace Database\Seeders;

use App\Models\Task;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "task"     => ["en-US" => "Look at your finances and find one way to save money"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go for a walk"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Organize a cluttered drawer"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to an escape room"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a list of things you are grateful for"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Study a foreign language"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Pick up litter around your favorite park"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make homemade ice cream"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Watch a movie you'd never usually watch"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Prepare a dish from a foreign culture"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Cook something together with someone"],
                "category" => "cook",
                "person"   => 2,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Mow your neighbor's lawn"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go on a fishing trip with some friends"],
                "category" => "social",
                "person"   => 3,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Repaint a room in your house"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go swimming with a friend"],
                "category" => "social",
                "person"   => 2,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Have a paper airplane contest with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Volunteer and help out at a senior center"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Host a movie marathon with some friends"],
                "category" => "social",
                "person"   => 3,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Plant a tree"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a daily journal"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take a class at your local community center that interests you"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Solve a Rubik's cube"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make your own LEGO creation"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to french braid hair"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go for a run"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Mow your lawn"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Hold a yard sale"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Have a jam session with your friends"],
                "category" => "music",
                "person"   => 5,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn the NATO phonetic alphabet"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/NATO_phonetic_alphabet"],
            ],
            [
                "task"     => ["en-US" => "Start a garden"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Organize your pantry"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to use a french press"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/French_press"],
            ],
            [
                "task"     => ["en-US" => "Invite some friends over for a game night"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to a concert with local artists with some friends"],
                "category" => "social",
                "person"   => 3,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Prepare a 72-hour kit"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => ["en-US" => "https://www.ready.gov/kit"],
            ],
            [
                "task"     => ["en-US" => "Do a jigsaw puzzle"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Jigsaw_puzzle"],
            ],
            [
                "task"     => ["en-US" => "Learn origami"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Volunteer at your local food bank"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Volunteer at your local food pantry"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn to play a new instrument"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Text a friend you haven't talked to in a long time"],
                "category" => "social",
                "person"   => 2,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn woodworking"],
                "category" => "DIY",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a note of appreciation to someone"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take a spontaneous road trip with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn Express.js"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://expressjs.com/"],
            ],
            [
                "task"     => ["en-US" => "Play basketball with a group of friends"],
                "category" => "social",
                "person"   => 5,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Listen to your favorite album"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Play a volleyball match with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Fill out a basketball bracket"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make bread from scratch"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Clean out your garage"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go see a Broadway production"],
                "category" => "fun",
                "person"   => 4,
                "cost"     => "$$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to a local thrift shop"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a handwritten letter to somebody"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Clean out your refrigerator"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a scrapbook with pictures of your favorite memories"],
                "category" => "DIY",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Shred old documents you don't need anymore"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Surprise your significant other with something considerate"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a simple musical instrument"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Listen to a new music genre"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn Javascript"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Color"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Play a game of Monopoly"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to write in shorthand"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take a hike at a local park"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a blog for something you're passionate about"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn Kotlin"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://kotlinlang.org/"],
            ],
            [
                "task"     => ["en-US" => "Go stargazing"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to play a new sport"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Create a compost pile"],
                "category" => "DIY",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Do yoga"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Donate blood at a local blood center"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://www.redcross.org/give-blood"],
            ],
            [
                "task"     => ["en-US" => "Go see a movie in theaters with a few friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Watch the sunset or the sunrise"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Plan a trip to another country"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a new friend"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a book you've never gotten around to reading"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to the library and find an interesting book"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how the internet works"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Have a photo session with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Organize your basement"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to use an Arduino"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Arduino"],
            ],
            [
                "task"     => ["en-US" => "Learn GraphQL"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://graphql.org/"],
            ],
            [
                "task"     => ["en-US" => "Learn how to fold a paper crane"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn a new recipe"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn to write with your nondominant hand"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn the Chinese erhu"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Find a DIY to do"],
                "category" => "DIY",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take your dog on a walk"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Visit a nearby museum"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Back up important computer files"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take a bubble bath"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Organize your music collection"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Give your pet ten minutes of focused attention"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to a music festival with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Memorize the fifty states and their capitals"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to a karaoke bar with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Uninstall unused apps from your devices"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a to-do list for your week"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Read a formal research paper on an interesting subject"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Have a picnic with some friends"],
                "category" => "social",
                "person"   => 3,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Have a bonfire with your close friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Hold a video game tournament with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Listen to a new podcast"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Explore a park you have never been to before"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Have a football scrimmage with some friends"],
                "category" => "social",
                "person"   => 8,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Organize your dresser"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Pot some plants and put them around your house"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Bake something you've never tried before"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn about the Golden Ratio"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Golden_ratio"],
            ],
            [
                "task"     => ["en-US" => "Draft your living will"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://www.investopedia.com/terms/l/livingwill.asp"],
            ],
            [
                "task"     => ["en-US" => "Create and follow a savings plan"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Plan a vacation you've always wanted to take"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to make an Alexa skill"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://developer.amazon.com/en-US/docs/alexa/custom-skills/steps-to-build-a-custom-skill.html"],
            ],
            [
                "task"     => ["en-US" => "Rearrange and organize your room"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Do something you used to do as a kid"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a band"],
                "category" => "music",
                "person"   => 4,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Sit in the dark and listen to your favorite music with no distractions"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a couch fort"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Compliment someone"],
                "category" => "social",
                "person"   => 2,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Conquer one of your fears"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn a new programming language"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Catch up with a friend over a lunch date"],
                "category" => "social",
                "person"   => 2,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Organize a bookshelf"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Find a charity and donate to it"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Do something nice for someone you care about"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Bake pastries for you and your neighbor"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Match your storage containers with their lids"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Create or update your resume"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Donate to your local food bank"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn the periodic table"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Periodic_table"],
            ],
            [
                "task"     => ["en-US" => "Play a video game"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn and play a new card game"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://www.pagat.com"],
            ],
            [
                "task"     => ["en-US" => "Visit your past teachers"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Watch a Khan Academy lecture on a subject of your choosing"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://www.khanacademy.org/"],
            ],
            [
                "task"     => ["en-US" => "Create a meal plan for the coming week"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Memorize a favorite quote or poem"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Pull a harmless prank on one of your friends"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Volunteer at a local animal shelter"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn to sew on a button"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a collection"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a poem"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a short story"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Wash your car"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Configure two-factor authentication on your accounts"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Multi-factor_authentication"],
            ],
            [
                "task"     => ["en-US" => "Shop at support your local farmers market"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn to greet someone in a new language"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a song"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Fix something that's broken in your house"],
                "category" => "DIY",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to a concert with some friends"],
                "category" => "social",
                "person"   => 4,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Meditate for five minutes"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make tie dye shirts"],
                "category" => "DIY",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to the gym"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Patronize a local independent restaurant"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Draw and color a Mandala"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Mandala"],
            ],
            [
                "task"     => ["en-US" => "Go on a long drive with no music"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Create a cookbook with your favorite recipes"],
                "category" => "cook",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to whistle with your fingers"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Practice coding in your favorite lanaguage"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a webinar on a topic of your choice"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take your cat on a walk"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to make a website"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Bake a pie with some friends"],
                "category" => "cook",
                "person"   => 3,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Draw something interesting"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Think of a new business idea"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a bucket list"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Go to a nail salon"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Catch up on world news"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Look at pictures and videos of cute animals"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Buy a new house decoration"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Take a caffeine nap"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn about a distributed version control system such as Git"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Distributed_version_control"],
            ],
            [
                "task"     => ["en-US" => "Take a nap"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Improve your touch typing"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Touch_typing"],
            ],
            [
                "task"     => ["en-US" => "Listen to music you haven't heard in a while"],
                "category" => "music",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Start a family tree"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Family_tree"],
            ],
            [
                "task"     => ["en-US" => "Learn Morse code"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Morse_code"],
            ],
            [
                "task"     => ["en-US" => "Organize your movie collection"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to beatbox"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "free",
                "links"    => ["en-US" => "https://en.wikipedia.org/wiki/Beatboxing"],
            ],
            [
                "task"     => ["en-US" => "Paint the first thing you see"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Try a food you don't like"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Learn how to iceskate or rollerskate"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Play a game of tennis with a friend"],
                "category" => "social",
                "person"   => 2,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Make a budget"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Watch a classic movie"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Write a thank you letter to an influential person in your life"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Research a topic you're interested in"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Create a personal website"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Contribute code or a monetary donation to an open-source software project"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "$",
                "links"    => ["en-US" => "https://github.com/explore"],
            ],
            [
                "task"     => ["en-US" => "Learn calligraphy"],
                "category" => "learn",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Binge watch a trending series"],
                "category" => "fun",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Teach your dog a new trick"],
                "category" => "resting",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Resolve a problem you've been putting off"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Clean out your closet and donate the clothes you've outgrown"],
                "category" => "charity",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Explore the nightlife of your city"],
                "category" => "social",
                "person"   => 1,
                "cost"     => "$",
                "links"    => null,
            ],
            [
                "task"     => ["en-US" => "Clean out your car"],
                "category" => "staying busy",
                "person"   => 1,
                "cost"     => "free",
                "links"    => null,
            ],
        ];

        foreach ($data as $task) {
            Task::create($task);
        }

    }
}
