<x-app-layout>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-4">
            <div class="bg-white sm:rounded-md p-12">
                <h1 class="text-xl font-bold">{{__('About and Imprint')}}</h1>
                <p>


                    Purpose: <br>
                    Welcome to our open source website! Our website is completely free to use by anyone, and we don't charge any fees. However, we do accept donations to help us
                    cover our hosting and development costs. We believe in open source software, and we actively encourage participation from our users. Thank you for choosing our
                    website! We hope you have a great
                    time learning about the implementation of an API and making the most of our website. <br>

                    This website is established to provide a small platform for testing and learning how to implement a small API. <br>
                    The website is intended for pure learning and testing purposes and will not be used for any commercial or other activities. <br>
                    This website is not responsible for any content generated by the users. We do not save or store
                    any user data, and we do not collect any personal data. <br>
                    This website is provided as-is, without any warranties or guarantees of any kind. We do not take any
                    responsibility for any losses or damages that may arise from using our website. <br>

                    This website does not store any user data. All user submitted tasks are collected anonymously and will not be used for any other purpose
                    other than the development and improvement of the Website. No task will be online before we read it and approve it in case of an offencive words or links <br>
                    Contribution and Bug Report: <br>

                    If you would like to contribute to the base code or submit a bug report, please do so through GitHub. <br>
                    This is the best way to ensure that your contribution or bug report is properly tracked and addressed in a timely manner. <br>
                    Please follow the instructions provided on the GitHub page when submitting your contribution or bug report. <br>
                    Cookies <br>

                    This website does not use cookies or any other tracking technologies, and does not store any user data. <br>
                    Contact: <br>
                    owned and operated by: Abdulsalam Emesh <br>
                    Email: contact@abdulsalam-emesh.me <br>

                </p>
            </div>
        </div>

    </div>
</x-app-layout>
