<x-app-layout>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-4">
            <div class="bg-white sm:rounded-md p-12 space-y-5">
                <h1 class="text-xl font-bold">{{__('About & Imprint')}}</h1>
                <p>{{__('Welcome to our What to do API open source website!')}}</p>

                <div class="space-y-2">
                    <h2 class="font-bold">{{__('Purpose')}}</h2>
                    <p>&#9679; {{__('Our website is completely free to use by anyone, and we don\'t charge any fees. However, we do accept donations to help us cover our hosting and development costs. We believe in open source software, and we actively encourage participation from our users. Thank you for choosing our website! We hope you have a great time learning about the implementation of an API and making the most of our website.')}}</p>
                    <p>&#9679; {{__('This website is established to provide a small platform for testing and learning how to implement a small API.')}}</p>
                    <p>&#9679; {{__('The website is intended for pure learning and testing purposes and will not be used for any commercial or other activities.')}}</p>
                    <p>&#9679; {{__('This website is not responsible for any content generated by the users. We do not save or store any user data, and we do not collect any personal data.')}}</p>
                    <p>
                        &#9679; {{__('This website is provided as-is, without any warranties or guarantees of any kind. We do not take any responsibility for any losses or damages that may arise from using our website.')}}</p>
                </div>
                <div class="space-y-2">
                    <h2 class="font-bold">{{__('Donations')}}</h2>
                    <a href="https://www.paypal.com/donate/?hosted_button_id=A7X8V8USXHUQ4" target="_blank"
                       class="group max-w-fit flex items-center bg-blue-500 hover:bg-blue-600 hover:shadow-[-4px_4px_0px_rgb(252,211,77)] transition-all duration-150 rounded px-2 py-1 space-x-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" class="h-8 w-auto fill-white group-hover:fill-[rgb(252,211,77)] transition-all duration-150">
                            <path
                                d="M186.3 258.2c0 12.2-9.7 21.5-22 21.5-9.2 0-16-5.2-16-15 0-12.2 9.5-22 21.7-22 9.3 0 16.3 5.7 16.3 15.5zM80.5 209.7h-4.7c-1.5 0-3 1-3.2 2.7l-4.3 26.7 8.2-.3c11 0 19.5-1.5 21.5-14.2 2.3-13.4-6.2-14.9-17.5-14.9zm284 0H360c-1.8 0-3 1-3.2 2.7l-4.2 26.7 8-.3c13 0 22-3 22-18-.1-10.6-9.6-11.1-18.1-11.1zM576 80v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V80c0-26.5 21.5-48 48-48h480c26.5 0 48 21.5 48 48zM128.3 215.4c0-21-16.2-28-34.7-28h-40c-2.5 0-5 2-5.2 4.7L32 294.2c-.3 2 1.2 4 3.2 4h19c2.7 0 5.2-2.9 5.5-5.7l4.5-26.6c1-7.2 13.2-4.7 18-4.7 28.6 0 46.1-17 46.1-45.8zm84.2 8.8h-19c-3.8 0-4 5.5-4.2 8.2-5.8-8.5-14.2-10-23.7-10-24.5 0-43.2 21.5-43.2 45.2 0 19.5 12.2 32.2 31.7 32.2 9 0 20.2-4.9 26.5-11.9-.5 1.5-1 4.7-1 6.2 0 2.3 1 4 3.2 4H200c2.7 0 5-2.9 5.5-5.7l10.2-64.3c.3-1.9-1.2-3.9-3.2-3.9zm40.5 97.9l63.7-92.6c.5-.5.5-1 .5-1.7 0-1.7-1.5-3.5-3.2-3.5h-19.2c-1.7 0-3.5 1-4.5 2.5l-26.5 39-11-37.5c-.8-2.2-3-4-5.5-4h-18.7c-1.7 0-3.2 1.8-3.2 3.5 0 1.2 19.5 56.8 21.2 62.1-2.7 3.8-20.5 28.6-20.5 31.6 0 1.8 1.5 3.2 3.2 3.2h19.2c1.8-.1 3.5-1.1 4.5-2.6zm159.3-106.7c0-21-16.2-28-34.7-28h-39.7c-2.7 0-5.2 2-5.5 4.7l-16.2 102c-.2 2 1.3 4 3.2 4h20.5c2 0 3.5-1.5 4-3.2l4.5-29c1-7.2 13.2-4.7 18-4.7 28.4 0 45.9-17 45.9-45.8zm84.2 8.8h-19c-3.8 0-4 5.5-4.3 8.2-5.5-8.5-14-10-23.7-10-24.5 0-43.2 21.5-43.2 45.2 0 19.5 12.2 32.2 31.7 32.2 9.3 0 20.5-4.9 26.5-11.9-.3 1.5-1 4.7-1 6.2 0 2.3 1 4 3.2 4H484c2.7 0 5-2.9 5.5-5.7l10.2-64.3c.3-1.9-1.2-3.9-3.2-3.9zm47.5-33.3c0-2-1.5-3.5-3.2-3.5h-18.5c-1.5 0-3 1.2-3.2 2.7l-16.2 104-.3.5c0 1.8 1.5 3.5 3.5 3.5h16.5c2.5 0 5-2.9 5.2-5.7L544 191.2v-.3zm-90 51.8c-12.2 0-21.7 9.7-21.7 22 0 9.7 7 15 16.2 15 12 0 21.7-9.2 21.7-21.5.1-9.8-6.9-15.5-16.2-15.5z"/>
                        </svg>
                        <span class="text-white group-hover:text-[rgb(252,211,77)] transition-all duration-150">{{__('Buy me a coffee')}} :)</span>
                    </a>
                </div>
                <div class="space-y-2">
                    <h2 class="font-bold">{{__('Contact')}}</h2>
                    <p>{{__('Owned and operated by:')}} Abdulsalam Emesh</p>
                    <p>Website: <a href="https://abdulsalam-emesh.me" target="_blank" class="text-blue-500 hover:text-blue-600">https://abdulsalam-emesh.me</a></p>
                    <a href="javascript:linkTo_UnCryptMailto('nbjmup;dpoubduAbcevmtbmbn.fnfti/nf');" class="block text-sm md:text-base">
                        {{ __('Email') }}: <span
                            class="hover:text-blue-600 text-blue-500  transition duration-150 encrypt-email">em.hseme-malasludba@tcatnoc</span>
                    </a>
                </div>
                <div class="space-y-2">
                    <h2 class="font-bold">{{__('User Contributions')}}</h2>
                    <p>{{__('This website does not store any user data. All user submitted tasks are collected anonymously and will not be used for any other purpose other than the development and improvement of the Website. No task will be online before we read it and approve it in case of any offensive words or links.')}}</p>
                </div>
                <div class="space-y-2">
                    <h2 class="font-bold">{{__('Code Contributions and Bug Reports')}}</h2>
                    <p>{{__('Github is the best way to ensure that your contribution or bug report is properly tracked and addressed in a timely manner. Please follow the instructions provided on the GitHub page when submitting your contribution or bug report.')}}</p>
                    <a href="https://github.com/abdulsalamemesh/what-to-do-api" target="_blank" class="text-blue-500 hover:text-blue-600">https://github.com/abdulsalamemesh/what-to-do-api</a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
